# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.runs/synth_1/.Xil/Vivado-12000-聂永欣のsurface/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/cyclecounter.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/dejittertop.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/differenciator.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/fsm.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/idlehandler.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/m60_counter.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/muldisp.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/rstreg.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/sec.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/smg.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/statectrl.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/timectrl.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/timereverse.v
      F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.srcs/sources_1/new/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "F:/桌面/西安交通大学/数字电子技术与微处理器/数字电子技术/数电实验/数电实验/大作业/chronopro/smg.runs/synth_1/.Xil/Vivado-12000-聂永欣のsurface/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
