# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache D:/Users/whxxjj/Documents/Vivado/XADC001/.Xil/Vivado-14900-LAPTOP-P8KFOD7P/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.cache/wt [current_project]
set_property parent.project_path D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/new/BCD_16.v
  D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/new/XADC_channel_1.v
  D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/new/XADC_result.v
  D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/new/bcd_7.v
  D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/new/clkdiv.v
  D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/new/outreg.v
  D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/new/select.v
  D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/new/wdnmd.v
}
read_ip -quiet d:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/constrs_1/new/wgnmd.xdc
set_property used_in_implementation false [get_files D:/Users/whxxjj/Documents/Vivado/XADC001/XADC001.srcs/constrs_1/new/wgnmd.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top wdnmd -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef wdnmd.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file wdnmd_utilization_synth.rpt -pb wdnmd_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
