# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.cache/wt [current_project]
set_property parent.project_path G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/Sec_pule_generator.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/XADC_channel_1.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/counter25.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/counter25_top.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/differenciator.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/duqu.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/edgecounter.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/fanqiezhong_top.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/pressadjuster.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/pwmctrl.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/state.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/xiaodoudong.v
  G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/new/proclocktop.v
}
read_ip -quiet G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all g:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/constrs_1/new/x.xdc
set_property used_in_implementation false [get_files G:/vivado_project/secretgarden/chineseseries/fanqiezhong_30_involvestar/AD_DA.srcs/constrs_1/new/x.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top proclocktop -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef proclocktop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file proclocktop_utilization_synth.rpt -pb proclocktop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
